package com.bfwk.model;

public class TradeOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.trade_id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    private Long tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.user_id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.total_money
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    private Double totalMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.trade_id
     *
     * @return the value of trade_order.trade_id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public Long getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.trade_id
     *
     * @param tradeId the value for trade_order.trade_id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public void setTradeId(Long tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.id
     *
     * @return the value of trade_order.id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.id
     *
     * @param id the value for trade_order.id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.user_id
     *
     * @return the value of trade_order.user_id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.user_id
     *
     * @param userId the value for trade_order.user_id
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.total_money
     *
     * @return the value of trade_order.total_money
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public Double getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.total_money
     *
     * @param totalMoney the value for trade_order.total_money
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }
}