package com.bfwk.mapper;

import com.bfwk.model.TradeOrder;
import com.bfwk.model.TradeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    long countByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    int deleteByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    int insert(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    int insertSelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    List<TradeOrder> selectByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbg.generated Thu Mar 01 11:31:23 CST 2018
     */
    int updateByExample(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);
}